name: Docker Image CI

on:
  push:
    branches: [ "stable", "develop" ]
    tags:
      - stable-*
      - develop-*
  pull_request:
    branches: [ "stable", "develop" ]

env:
  BRANCH: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: get latest commit id
      run: echo "COMMIT_ID=$(curl "https://akkoma.dev/api/v1/repos/AkkomaGang/akkoma/branches/${{ env.BRANCH }}" | jq -r '.commit.id')" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: teslamint
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        # List of build-time variables
        build-args: "PLEROMA_VER=${{ env.COMMIT_ID }}"
        platforms: "linux/amd64,linux/arm64"
        tags: "teslamint/akkoma:${{ env.BRANCH }},teslamint/akkoma:${{ env.COMMIT_ID }}"
